# Abi-tester multi-contract config, used for testing.

[settings]
proxy-paths = ["src/abi_proxy.rs"]
main = "main"

[contracts.main]
name = "abi-tester"

[contracts.external-view]
name = "abi-tester-ev"
external-view = true
add-unlabelled = false
add-labels = ["test-external-view"]
add-endpoints = ["payable_any_token", "label_a"] # labels can be bypassed, endpoints added directly
