[package]
name = "interactor"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dependencies.multiversx-sc-snippets]
path = "../../../../../framework/snippets"
