[package]
name = "multiversx-sdk-reqwest"
version = "0.6.1"
edition = "2021"

authors = [
    "MultiversX <contact@multiversx.com>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/multiversx/mx-sdk-rs"
homepage = "https://multiversx.com/"
documentation = "https://docs.multiversx.com/"
description = "SDK for interacting with the MultiversX blockchain"
categories = ["cryptography::cryptocurrencies", "api-bindings"]
keywords = ["multiversx", "blockchain", "sdk", "api"]

[dependencies]
tokio = { version = "1.24", features = ["full"] }
reqwest = { version = "0.12", features = ["blocking", "json"] }
anyhow = "1.0.44"
hex = "0.4.3"
itertools = "0.13.0"
log = "0.4.17"

# TEMP
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.68", features = ["preserve_order"] }

[dependencies.multiversx-sdk]
version = "=0.6.1"
path = "../core"
