[package]
name = "gas_tests"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/gas_tests.rs"

[dependencies.multiversx-sc]
version = "0.57.0"
path = "../../../framework/base"

[dev-dependencies.multiversx-sc-scenario]
version = "0.57.0"
path = "../../../framework/scenario"

[features]
wasmer-prod = ["multiversx-sc-scenario/wasmer-prod"]
wasmer-experimental = ["multiversx-sc-scenario/wasmer-experimental"]

[workspace]
members = ["."]
