[package]
name = "multiversx-chain-vm-wasmer-prod"
version = "0.0.0"
edition = "2021"
publish = false

description = "MultiversX VM adapter for the Wasmer Production executor"

[lib]
path = "src/wasmer_prod.rs"

[dependencies.multiversx-chain-core]
version = "=0.15.0"
path = "../core"


[dependencies.multiversx-chain-vm]
version = "=0.15.0"
path = "../vm"

[dependencies.multiversx-chain-vm-executor]
version = "0.4.0"
git = "https://github.com/multiversx/mx-vm-executor-rs"
rev = "2509b7383368a2cb8d716bf3f43396ff28e9221f"

[dependencies.multiversx-chain-vm-executor-wasmer]
version = "0.4.0"
default-features = true
# features = ["multiversx-chain-vm-executor-published"]
git = "https://github.com/multiversx/mx-vm-executor-rs"
rev = "2509b7383368a2cb8d716bf3f43396ff28e9221f"

[workspace]
members = ["."]