[[bin]]
name = "basic-interact-sys-calls"
path = "src/basic_interact.rs"

[package]
name = "basic-interact-sys-calls"
version = "0.0.0"
publish = false
edition = "2021"
authors = ["you"]

[dependencies]
toml = "0.8.6"

[dependencies.clap]
version = "4.4.7"
features = ["derive"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.multiversx-sc-snippets]
version = "0.52.3"
