name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@dcb4ee50efcb83709d5af181232f4380d931eeae
    with:
      rust-toolchain: stable
      path-to-sc-meta: framework/meta
      mx-scenario-go-version: v2.1.0-alpha
      coverage-args: --ignore-filename-regex='meta/src' --ignore-filename-regex='wasm-adapter' --ignore-filename-regex='benchmarks/' --ignore-filename-regex='tests/' --output ./coverage.md
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}