name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts (nightly)
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@a6f57c43a0ae9c6d3bafffa01b5aa46dea0c3d3e
    with:
      rust-toolchain: nightly-2023-12-11
      path-to-sc-meta: framework/meta
      enable-contracts-size-report: false
      mx-scenario-go-version: v2.1.0-alpha
      coverage-args: --ignore-filename-regex='meta/src' --ignore-filename-regex='wasm-adapter' --ignore-filename-regex='benchmarks/' --ignore-filename-regex='tests/' --output ./coverage.md
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}