name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Slow
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go mod tidy
      - name: Slow tests
        run: make slow-tests