name: Windows CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  windows_build_and_test:
    name: Build and test on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if required Visual Studio components are installed
        id: check_vs_tools
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $vs_installer = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
          if (Test-Path $vs_installer) {
            $installed = & $vs_installer -latest -products * `
              -requires Microsoft.VisualStudio.Workload.VCTools `
              Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
              Microsoft.VisualStudio.Component.Windows10SDK `
              Microsoft.VisualStudio.Component.Windows11SDK `
              Microsoft.VisualStudio.Component.CMake `
              -property installationPath

            if ($installed) {
              echo "All required components are installed"
              echo "VS_INSTALLED=true" >> $GITHUB_ENV
            } else {
              echo "VS_INSTALLED=false" >> $GITHUB_ENV
            }
          } else {
            echo "VS_INSTALLED=false" >> $GITHUB_ENV
          }

      - name: Install VS Build Tools
        if: env.VS_INSTALLED != 'true'
        shell: pwsh
        run: |
          choco install visualstudio2022buildtools --package-parameters `
            "--add Microsoft.VisualStudio.Workload.VCTools `
            --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 `
            --add Microsoft.VisualStudio.Component.Windows10SDK `
            --add Microsoft.VisualStudio.Component.Windows11SDK `
            --add Microsoft.VisualStudio.Component.CMake `
            --includeRecommended --quiet --wait"

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install sc-meta
        run: cargo install multiversx-sc-meta

      - name: Run sc-meta commands
        run: |
          cd contracts/feature-tests/basic-features
          sc-meta all build
          sc-meta all proxy
          sc-meta all snippets
          cd ../
          sc-meta new --template empty --name windows-template-test-sc
