[settings]
main = "main"
proxy-paths = [
    "../forwarder/src/vault_proxy.rs",
    "../promises-features/src/vault_proxy.rs",
    "../recursive-caller/src/vault_proxy.rs"
]

[contracts.main]
name = "vault"
add-unlabelled = true
add-labels = ["upgrade"]

[contracts.promises]
name = "vault-promises"
add-unlabelled = true
add-labels = ["promises-endpoint"]

[contracts.upgrade]
name = "vault-upgrade"
add-unlabelled = false
add-labels = ["upgrade"]
